name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'codewars/coq' }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          # Make the image available in next step
          load: true
          tags: ghcr.io/codewars/coq:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Passing Example
        run: bin/run passing
