# Build and push a Docker image to GitHub Container Registry when
# a new tag is pushed.
name: Push Image

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push-image:
    if: ${{ github.repository == 'codewars/coq' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/coq:latest
            ghcr.io/${{ github.repository_owner }}/coq:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
